version: '3.7'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:9092
    volumes:
      - ./backend/:/app/backend
    ports:
      - 9092:9092
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=doran
      - SQL_USER=doran_user
      - SQL_PASSWORD=doran_pw
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db
  db:
    image: postgres:11.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=doran_user
      - POSTGRES_PASSWORD=doran_pw
      - POSTGRES_DB=doran
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
  postgres_data: